import { DEFAULT_PROPERTY_ID } from './supabase';
import type { Booking, Expense, Damage, RecurringBillTemplate, Property } from '@/types/database';

export const INITIAL_PROPERTY: Property = {
  id: DEFAULT_PROPERTY_ID,
  name: 'Reserva del Mar II',
  address: 'Playa Salguero, Santa Marta',
  city: 'Santa Marta',
  currency: 'COP',
  default_nightly_rate: 280000,
  default_cleaning_fee: 60000,
  monthly_revenue_target: 3000000,
  management_fee_rate: 20.0,
  check_in_time: '15:00',
  check_out_time: '11:00',
};

export const INITIAL_TEMPLATES: RecurringBillTemplate[] = [
  {
    id: 'tmpl-1',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'hoa_administration',
    expense_type: 'fixed_monthly',
    name: 'Administración del Edificio',
    default_amount: 380000,
    typical_due_day: 10,
    annual_due_month: null,
    is_active: true,
    notes: 'Pago antes del día 10 para descuento de pronto pago',
  },
  {
    id: 'tmpl-2',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'internet_cable',
    expense_type: 'fixed_monthly',
    name: 'Internet Fibra 300MB (Tigo)',
    default_amount: 125000,
    typical_due_day: 15,
    annual_due_month: null,
    is_active: true,
    notes: 'Débito automático bancario',
  },
  {
    id: 'tmpl-3',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'electricity',
    expense_type: 'utility_monthly',
    name: 'Energía / Luz (EPM)',
    default_amount: 290000,
    typical_due_day: 20,
    annual_due_month: null,
    is_active: true,
    notes: 'Medidor de luz del apartamento',
  },
  {
    id: 'tmpl-4',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'water',
    expense_type: 'utility_monthly',
    name: 'Agua y Alcantarillado (EPM)',
    default_amount: 110000,
    typical_due_day: 20,
    annual_due_month: null,
    is_active: true,
    notes: 'Factura conjunta EPM',
  },
  {
    id: 'tmpl-5',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'gas',
    expense_type: 'utility_monthly',
    name: 'Gas Domiciliario (EPM)',
    default_amount: 35000,
    typical_due_day: 20,
    annual_due_month: null,
    is_active: true,
    notes: 'Calentador y estufa',
  },
  {
    id: 'tmpl-6',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'insurance_annual',
    expense_type: 'annual',
    name: 'Póliza Todo Riesgo Apartamento (SURA)',
    default_amount: 1350000,
    typical_due_day: 15,
    annual_due_month: 6,
    is_active: true,
    notes: 'Vence el 15 de Junio de cada año',
  },
];

const RAW_BOOKINGS: Omit<Booking, 'management_fee' | 'owner_payout'>[] = [
  // Completed Bookings (from airbnb_.csv)
  {
    id: 'b-001',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMTW8FZT3Y',
    guest_name: 'Laura Estefanía Gomez',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-09-11',
    check_out: '2026-09-14',
    number_of_nights: 3,
    nightly_rate: 106106,
    gross_amount: 378815,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 71993,
    taxes_withheld: 0,
    net_payout: 318317,
    status: 'checked_in',
    payout_status: 'paid',
    payout_date: '2026-09-12',
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-002',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMB8HF8EJZ',
    guest_name: 'Liliana Nieto',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-09-09',
    check_out: '2026-09-11',
    number_of_nights: 2,
    nightly_rate: 128531,
    gross_amount: 305917,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 58139,
    taxes_withheld: 0,
    net_payout: 257061,
    status: 'completed',
    payout_status: 'paid',
    payout_date: '2026-09-10',
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-003',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMBC5JQW32',
    guest_name: 'Laura Marcela Florez Hernandez',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-08-27',
    check_out: '2026-08-31',
    number_of_nights: 4,
    nightly_rate: 127491,
    gross_amount: 606887,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 115337,
    taxes_withheld: 0,
    net_payout: 509965,
    status: 'completed',
    payout_status: 'paid',
    payout_date: '2026-08-28',
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-004',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMRC3M4SAR',
    guest_name: 'Nicolás Martín Sanchez',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-07-22',
    check_out: '2026-07-26',
    number_of_nights: 4,
    nightly_rate: 122159,
    gross_amount: 599148,
    cleaning_fee_collected: 0,
    airbnb_service_fee: 110513,
    taxes_withheld: 0,
    net_payout: 488635,
    status: 'completed',
    payout_status: 'paid',
    payout_date: '2026-07-23',
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-005',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMRC2CNPYW',
    guest_name: 'Laura Rengifo',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-07-14',
    check_out: '2026-07-18',
    number_of_nights: 4,
    nightly_rate: 96769,
    gross_amount: 474619,
    cleaning_fee_collected: 0,
    airbnb_service_fee: 87544,
    taxes_withheld: 0,
    net_payout: 387076,
    status: 'completed',
    payout_status: 'paid',
    payout_date: '2026-07-15',
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-006',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMRPENA2H2',
    guest_name: 'David Jara',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-07-10',
    check_out: '2026-07-12',
    number_of_nights: 2,
    nightly_rate: 124554,
    gross_amount: 305448,
    cleaning_fee_collected: 0,
    airbnb_service_fee: 56340,
    taxes_withheld: 0,
    net_payout: 249108,
    status: 'completed',
    payout_status: 'paid',
    payout_date: '2026-07-11',
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },

  // Pending & Upcoming Bookings (from airbnb_pending.csv)
  {
    id: 'b-007',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMQCK3QCSA',
    guest_name: 'Julian Ruiz Ortiz',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-09-14',
    check_out: '2026-09-17',
    number_of_nights: 3,
    nightly_rate: 123528,
    gross_amount: 441017,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 83816,
    taxes_withheld: 0,
    net_payout: 370585,
    status: 'confirmed',
    payout_status: 'pending',
    payout_date: null,
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-008',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMPNJPNY2E',
    guest_name: 'Juan Camilo Albadan',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-09-19',
    check_out: '2026-09-21',
    number_of_nights: 2,
    nightly_rate: 142721,
    gross_amount: 339693,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 64558,
    taxes_withheld: 0,
    net_payout: 285443,
    status: 'confirmed',
    payout_status: 'pending',
    payout_date: null,
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-009',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMTYRYAWPK',
    guest_name: 'Juan Amaya',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-09-25',
    check_out: '2026-09-28',
    number_of_nights: 3,
    nightly_rate: 116828,
    gross_amount: 417094,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 79267,
    taxes_withheld: 0,
    net_payout: 350483,
    status: 'confirmed',
    payout_status: 'pending',
    payout_date: null,
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-010',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMTT3W59NM',
    guest_name: 'Ale Cortes Velez',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-10-01',
    check_out: '2026-10-03',
    number_of_nights: 2,
    nightly_rate: 146799,
    gross_amount: 349398,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 66402,
    taxes_withheld: 0,
    net_payout: 293598,
    status: 'confirmed',
    payout_status: 'pending',
    payout_date: null,
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-011',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMKBMQQPQW',
    guest_name: 'Sergio Ivan Santos Mora',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-10-06',
    check_out: '2026-10-11',
    number_of_nights: 5,
    nightly_rate: 113769,
    gross_amount: 676959,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 128654,
    taxes_withheld: 0,
    net_payout: 568846,
    status: 'confirmed',
    payout_status: 'pending',
    payout_date: null,
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-012',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMF49J3DTD',
    guest_name: 'Julio Cesar Panesso Marulanda',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-10-16',
    check_out: '2026-10-18',
    number_of_nights: 2,
    nightly_rate: 135381,
    gross_amount: 322223,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 61237,
    taxes_withheld: 0,
    net_payout: 270763,
    status: 'confirmed',
    payout_status: 'pending',
    payout_date: null,
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-013',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMZR9TMDBD',
    guest_name: 'Harold Lizarazo Molina',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-10-18',
    check_out: '2026-10-21',
    number_of_nights: 3,
    nightly_rate: 120294,
    gross_amount: 429468,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 81619,
    taxes_withheld: 0,
    net_payout: 360881,
    status: 'confirmed',
    payout_status: 'pending',
    payout_date: null,
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
  {
    id: 'b-014',
    property_id: DEFAULT_PROPERTY_ID,
    airbnb_confirmation_code: 'HMD5MAZ48J',
    guest_name: 'Victoria Alexandra Hernandez',
    guest_phone: null,
    number_of_guests: 2,
    check_in: '2026-10-23',
    check_out: '2026-10-25',
    number_of_nights: 2,
    nightly_rate: 128449,
    gross_amount: 305723,
    cleaning_fee_collected: 60000,
    airbnb_service_fee: 58102,
    taxes_withheld: 0,
    net_payout: 256898,
    status: 'confirmed',
    payout_status: 'pending',
    payout_date: null,
    source: 'airbnb',
    notes: 'Reserva del Mar II',
  },
];

export const INITIAL_BOOKINGS: Booking[] = RAW_BOOKINGS.map((b) => {
  const cleaningFee = Number(b.cleaning_fee_collected) || 0;
  const accommodationBase = Math.max(0, b.net_payout - cleaningFee);
  const management_fee = Math.round(accommodationBase * 0.20);
  const owner_payout = Math.round(accommodationBase * 0.80);
  const nightly_rate =
    b.number_of_nights > 0 ? Math.round(owner_payout / b.number_of_nights) : b.nightly_rate;
  return {
    ...b,
    management_fee,
    owner_payout,
    nightly_rate,
  };
});

export const INITIAL_EXPENSES: Expense[] = [
  // August Fixed & Utilities
  {
    id: 'exp-01',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'hoa_administration',
    expense_type: 'fixed_monthly',
    description: 'Administración Edificio - Agosto 2026',
    amount: 380000,
    date: '2026-08-05',
    due_date: '2026-08-10',
    billing_month: '2026-08',
    payment_status: 'paid',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: 'Pagado por transferencia Bancolombia',
  },
  {
    id: 'exp-02',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'internet_cable',
    expense_type: 'fixed_monthly',
    description: 'Internet Fibra Óptica - Agosto 2026',
    amount: 125000,
    date: '2026-08-14',
    due_date: '2026-08-15',
    billing_month: '2026-08',
    payment_status: 'paid',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: 'Débito automático',
  },
  {
    id: 'exp-03',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'electricity',
    expense_type: 'utility_monthly',
    description: 'Factura EPM Energía / Luz - Agosto 2026',
    amount: 275000,
    date: '2026-08-18',
    due_date: '2026-08-20',
    billing_month: '2026-08',
    payment_status: 'paid',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: null,
  },
  {
    id: 'exp-04',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'water',
    expense_type: 'utility_monthly',
    description: 'Factura EPM Agua y Alcantarillado - Agosto 2026',
    amount: 105000,
    date: '2026-08-18',
    due_date: '2026-08-20',
    billing_month: '2026-08',
    payment_status: 'paid',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: null,
  },
  {
    id: 'exp-05',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'gas',
    expense_type: 'utility_monthly',
    description: 'Factura EPM Gas - Agosto 2026',
    amount: 32000,
    date: '2026-08-18',
    due_date: '2026-08-20',
    billing_month: '2026-08',
    payment_status: 'paid',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: null,
  },
  // Cleanings
  {
    id: 'exp-06',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'cleaning_laundry',
    expense_type: 'per_stay',
    description: 'Limpieza y lavandería - Salida David Miller',
    amount: 90000,
    date: '2026-08-06',
    due_date: null,
    billing_month: '2026-08',
    payment_status: 'paid',
    is_recurring: false,
    recurrence_period: null,
    linked_booking_id: 'b-001',
    receipt_url: null,
    notes: 'Pago a señora de limpieza',
  },
  {
    id: 'exp-07',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'cleaning_laundry',
    expense_type: 'per_stay',
    description: 'Limpieza y lavandería - Salida Camila Montoya',
    amount: 90000,
    date: '2026-08-16',
    due_date: null,
    billing_month: '2026-08',
    payment_status: 'paid',
    is_recurring: false,
    recurrence_period: null,
    linked_booking_id: 'b-002',
    receipt_url: null,
    notes: null,
  },
  // September Checklist
  {
    id: 'exp-08',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'hoa_administration',
    expense_type: 'fixed_monthly',
    description: 'Administración Edificio - Septiembre 2026',
    amount: 380000,
    date: '2026-09-08',
    due_date: '2026-09-10',
    billing_month: '2026-09',
    payment_status: 'paid',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: 'Pagado en fecha oportuna',
  },
  {
    id: 'exp-09',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'internet_cable',
    expense_type: 'fixed_monthly',
    description: 'Internet Fibra Óptica - Septiembre 2026',
    amount: 125000,
    date: '2026-09-14',
    due_date: '2026-09-15',
    billing_month: '2026-09',
    payment_status: 'paid',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: null,
  },
  {
    id: 'exp-10',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'electricity',
    expense_type: 'utility_monthly',
    description: 'Factura EPM Energía / Luz - Septiembre 2026',
    amount: 295000,
    date: '2026-09-13',
    due_date: '2026-09-20',
    billing_month: '2026-09',
    payment_status: 'pending',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: 'Pendiente de pago antes del 20',
  },
  {
    id: 'exp-11',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'water',
    expense_type: 'utility_monthly',
    description: 'Factura EPM Agua y Alcantarillado - Septiembre 2026',
    amount: 115000,
    date: '2026-09-13',
    due_date: '2026-09-20',
    billing_month: '2026-09',
    payment_status: 'pending',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: null,
  },
  {
    id: 'exp-12',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'gas',
    expense_type: 'utility_monthly',
    description: 'Factura EPM Gas - Septiembre 2026',
    amount: 34000,
    date: '2026-09-13',
    due_date: '2026-09-20',
    billing_month: '2026-09',
    payment_status: 'pending',
    is_recurring: true,
    recurrence_period: 'monthly',
    linked_booking_id: null,
    receipt_url: null,
    notes: null,
  },
  // Occasional Restock (Insumos)
  {
    id: 'exp-13',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'supplies_restock',
    expense_type: 'occasional',
    description: 'Compra Éxito: Café Juan Valdez, azúcar, papel higiénico x12, jabón Dove líquido',
    amount: 145000,
    date: '2026-09-01',
    due_date: null,
    billing_month: '2026-09',
    payment_status: 'paid',
    is_recurring: false,
    recurrence_period: null,
    linked_booking_id: null,
    receipt_url: null,
    notes: 'Reposición para el mes',
  },
  // Annual Insurance
  {
    id: 'exp-14',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'insurance_annual',
    expense_type: 'annual',
    description: 'Póliza Seguro de Hogar Todo Riesgo Apto 502 (SURA 2026-2027)',
    amount: 1350000,
    date: '2026-06-15',
    due_date: '2026-06-15',
    billing_month: '2026-06',
    payment_status: 'paid',
    is_recurring: true,
    recurrence_period: 'yearly',
    linked_booking_id: null,
    receipt_url: null,
    notes: 'Póliza vigente hasta Junio 2027',
  },
];

export const INITIAL_DAMAGES: Damage[] = [
  {
    id: 'dmg-01',
    property_id: DEFAULT_PROPERTY_ID,
    linked_booking_id: 'b-001',
    title: 'Copas de cristal rotas y mancha en alfombra',
    description: 'Al hacer el checkout se encontraron 2 copas rotas en el balcón y derrame de vino tinto en la alfombra de la sala.',
    date_discovered: '2026-08-06',
    severity: 'medium',
    estimated_repair_cost: 160000,
    actual_repair_cost: 145000,
    reimbursement_amount: 145000,
    claim_status: 'reimbursed',
    aircover_case_number: 'AC-98214',
    resolution_notes: 'Huésped admitió el accidente y pagó el valor de inmediato por la app de Airbnb.',
    photo_urls: [],
    linked_expense_id: null,
  },
  {
    id: 'dmg-02',
    property_id: DEFAULT_PROPERTY_ID,
    linked_booking_id: 'b-004',
    title: 'Control remoto de Smart TV quebrado',
    description: 'Control de la TV de la habitación principal partido con tapa de pilas rota.',
    date_discovered: '2026-09-08',
    severity: 'low',
    estimated_repair_cost: 65000,
    actual_repair_cost: 65000,
    reimbursement_amount: 0,
    claim_status: 'guest_contacted',
    aircover_case_number: null,
    resolution_notes: 'Esperando respuesta del huésped Sarah Connor para reembolso del repuesto original.',
    photo_urls: [],
    linked_expense_id: null,
  },
];
