import { DEFAULT_PROPERTY_ID } from './supabase';
import type { Booking, Expense, Damage, RecurringBillTemplate, Property } from '@/types/database';

export const INITIAL_PROPERTY: Property = {
  id: DEFAULT_PROPERTY_ID,
  name: 'Reserva del Mar II',
  address: 'Playa Salguero, Santa Marta',
  city: 'Santa Marta',
  currency: 'COP',
  default_nightly_rate: 280000,
  default_cleaning_fee: 60000,
  monthly_revenue_target: 3000000,
  management_fee_rate: 20.0,
  check_in_time: '15:00',
  check_out_time: '11:00',
};

export const INITIAL_TEMPLATES: RecurringBillTemplate[] = [
  {
    id: 'tmpl-1',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'hoa_administration',
    expense_type: 'fixed_monthly',
    name: 'Administración del Edificio',
    default_amount: 380000,
    typical_due_day: 10,
    annual_due_month: null,
    is_active: true,
    notes: 'Pago antes del día 10 para descuento de pronto pago',
  },
  {
    id: 'tmpl-2',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'internet_cable',
    expense_type: 'fixed_monthly',
    name: 'Internet Fibra 300MB (Tigo)',
    default_amount: 125000,
    typical_due_day: 15,
    annual_due_month: null,
    is_active: true,
    notes: 'Débito automático bancario',
  },
  {
    id: 'tmpl-3',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'electricity',
    expense_type: 'utility_monthly',
    name: 'Energía / Luz (EPM)',
    default_amount: 290000,
    typical_due_day: 20,
    annual_due_month: null,
    is_active: true,
    notes: 'Medidor de luz del apartamento',
  },
  {
    id: 'tmpl-4',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'water',
    expense_type: 'utility_monthly',
    name: 'Agua y Alcantarillado (EPM)',
    default_amount: 110000,
    typical_due_day: 20,
    annual_due_month: null,
    is_active: true,
    notes: 'Factura conjunta EPM',
  },
  {
    id: 'tmpl-5',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'gas',
    expense_type: 'utility_monthly',
    name: 'Gas Domiciliario (EPM)',
    default_amount: 35000,
    typical_due_day: 20,
    annual_due_month: null,
    is_active: true,
    notes: 'Calentador y estufa',
  },
  {
    id: 'tmpl-6',
    property_id: DEFAULT_PROPERTY_ID,
    category: 'insurance_annual',
    expense_type: 'annual',
    name: 'Póliza Todo Riesgo Apartamento (SURA)',
    default_amount: 1350000,
    typical_due_day: 15,
    annual_due_month: 6,
    is_active: true,
    notes: 'Vence el 15 de Junio de cada año',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [];

export const INITIAL_EXPENSES: Expense[] = [];

export const INITIAL_DAMAGES: Damage[] = [];

export const INITIAL_GUEST_GUIDE: import('@/types/database').GuestGuideData = {
  property_id: DEFAULT_PROPERTY_ID,
  welcome_title: '¡Bienvenido a Reserva del Mar II!',
  welcome_message: 'Esperamos que disfrutes al máximo de tu estadía frente al mar en Santa Marta. Aquí tienes toda la información clave para una experiencia perfecta e inolvidable.',
  apartment_number: 'Apto 502',
  address: 'Carrera 1 # 24-45, Playa Salguero, Santa Marta, Colombia',
  maps_url: 'https://maps.google.com/?q=Playa+Salguero+Santa+Marta',
  
  // Wi-Fi
  wifi_ssid: 'ReservaMar_502_5G',
  wifi_password: 'PlayaSalguero2026!',
  
  // Access & Keys
  show_access_code: true,
  access_code: '4820 #',
  access_instructions: 'Al llegar a la portería principal del edificio, indica tu nombre completo y número de cédula/pasaporte. El vigilante te entregará las manillas del conjunto. En la puerta del apto 502, toca la pantalla de la cerradura táctil para encenderla, ingresa el código y presiona la tecla #.',
  check_in_time: '15:00',
  check_out_time: '11:00',
  check_out_instructions: 'Por favor apaga los aires acondicionados y luces, deposita la basura en el shut de basuras del piso (frente a los ascensores) y cierra la puerta jalando firmemente hasta escuchar el pitido de seguro. ¡Buen viaje de regreso!',
  
  // Host Contact
  host_name: 'Axel Werner',
  host_phone: '+57 300 123 4567',
  host_email: 'contacto@reservaaptos.com',
  
  // Building & Services
  building_amenities: [
    'Piscinas infinitas (Piso 1 y Rooftop)',
    'Acceso directo privado a la playa',
    'Jacuzzis climatizados',
    'Gimnasio con vista al mar (Piso 18)',
    'Zona de sauna y turco',
    'Canchas de squash',
    'Seguridad y recepción 24 horas',
  ],
  house_rules: [
    {
      id: 'hr-1',
      icon: 'Volume2',
      title: 'Horas de Silencio y Tranquilidad',
      description: 'Por convivencia del conjunto, el volumen de música y ruidos debe ser moderado después de las 10:00 PM.',
    },
    {
      id: 'hr-2',
      icon: 'CigaretteOff',
      title: 'Espacio 100% Libre de Humo',
      description: 'Está estrictamente prohibido fumar o vapear dentro del apartamento y en los balcones.',
    },
    {
      id: 'hr-3',
      icon: 'Users',
      title: 'Registro de Visitantes',
      description: 'Solo las personas registradas en la reserva tienen permitido el ingreso a las instalaciones y zonas comunes.',
    },
    {
      id: 'hr-4',
      icon: 'Sparkles',
      title: 'Cuidado de Toallas y Lencería',
      description: 'Las toallas blancas son de uso exclusivo para el interior del apto. Para la piscina y playa, favor usar las toallas azules provistas.',
    },
  ],
  appliances: [
    {
      id: 'app-1',
      title: 'Aires Acondicionados',
      icon: 'AirVent',
      steps: [
        'Usa el control remoto apuntando directamente al split.',
        'Recomendamos temperatura en 22°C - 24°C modo "COOL" (ícono de copo de nieve).',
        'Mantén ventanas y puertas corredizas cerradas para optimizar el enfriamiento.',
      ],
      tips: 'Apágalos al salir del apartamento para proteger los equipos y evitar sobrecalentamiento.',
    },
    {
      id: 'app-2',
      title: 'Smart TV & Streaming',
      icon: 'Tv',
      steps: [
        'Enciende la pantalla con el botón rojo del control.',
        'Dispones de aplicaciones como Netflix, YouTube y Prime Video.',
        'Puedes iniciar sesión con tus propias cuentas personales.',
      ],
      tips: 'Al hacer check-out se cierran automáticamente las sesiones activas.',
    },
    {
      id: 'app-3',
      title: 'Agua Caliente (Calentador)',
      icon: 'Flame',
      steps: [
        'El calentador es automático y se activa con la presión del agua.',
        'Gira la llave de la ducha completamente hacia la izquierda y espera 30 segundos.',
      ],
      tips: 'Si sientes el agua demasiado caliente, mezcla suavemente con la llave derecha.',
    },
    {
      id: 'app-4',
      title: 'Torre Lavadora / Secadora',
      icon: 'Waves',
      steps: [
        'Coloca la ropa sin sobrecargar el tambor.',
        'Añade una tapa de detergente líquido en el compartimento superior.',
        'Selecciona el ciclo "Lavado Rápido 30min" o "Normal" y presiona Inicio.',
      ],
      tips: 'Encuentras detergente de cortesía en el mueble bajo el lavadero.',
    },
  ],
  key_distances: [
    {
      id: 'dist-1',
      name: 'Aeropuerto Internacional Simón Bolívar (SMR)',
      category: 'airport',
      distance: '10 km',
      travel_time: '15-20 min en taxi',
      description: 'Terminal aérea con vuelos nacionales y conexiones internacionales.',
      icon: 'Plane',
      maps_url: 'https://maps.google.com/?q=Aeropuerto+Simon+Bolivar+Santa+Marta',
    },
    {
      id: 'dist-2',
      name: 'Centro de El Rodadero',
      category: 'center',
      distance: '1.5 km',
      travel_time: '5 min en auto / 15 min a pie',
      description: 'Boulevard comercial, restaurantes, cajeros automáticos y vida nocturna.',
      icon: 'Store',
      maps_url: 'https://maps.google.com/?q=El+Rodadero+Santa+Marta',
    },
    {
      id: 'dist-3',
      name: 'Centro Histórico de Santa Marta',
      category: 'center',
      distance: '7.5 km',
      travel_time: '15-20 min en taxi',
      description: 'Parque de los Novios, Marina Internacional, Catedral, museos y arquitectura colonial.',
      icon: 'Landmark',
      maps_url: 'https://maps.google.com/?q=Centro+Historico+Santa+Marta',
    },
    {
      id: 'dist-4',
      name: 'Hospital / Urgencias (Clínica Portoazul / Prado)',
      category: 'hospital',
      distance: '3.5 km',
      travel_time: '8-10 min en taxi',
      description: 'Atención médica prioritaria, centro de urgencias 24/7 y farmacia especializada.',
      icon: 'HeartPulse',
      maps_url: 'https://maps.google.com/?q=Clinica+Portoazul+Santa+Marta',
    },
    {
      id: 'dist-5',
      name: 'Playa Salguero',
      category: 'beach',
      distance: '50 metros',
      travel_time: '1 min a pie (Acceso directo)',
      description: 'Playa tranquila, amplia y con atardeceres mágicos, justo saliendo del edificio.',
      icon: 'Waves',
      maps_url: 'https://maps.google.com/?q=Playa+Salguero+Santa+Marta',
    },
    {
      id: 'dist-6',
      name: 'Playa El Rodadero',
      category: 'beach',
      distance: '1.5 km',
      travel_time: '5 min en auto / 15 min a pie',
      description: 'La playa turística más icónica de Santa Marta, con carpas y deportes acuáticos.',
      icon: 'Sun',
      maps_url: 'https://maps.google.com/?q=Playa+El+Rodadero',
    },
    {
      id: 'dist-7',
      name: 'Embarcadero a Playa Blanca & Acuario',
      category: 'beach',
      distance: '2 km (Muelle)',
      travel_time: '7 min en auto + lancha',
      description: 'Punto de salida de lanchas autorizadas hacia Playa Blanca, Acuario y Playa Cristal.',
      icon: 'Ship',
      maps_url: 'https://maps.google.com/?q=Muelle+Turistico+Rodadero',
    },
    {
      id: 'dist-8',
      name: 'Parque Nacional Natural Tayrona',
      category: 'attraction',
      distance: '38 km',
      travel_time: '45-50 min en auto / tour',
      description: 'Entrada El Zaino: una de las mayores joyas ecológicas y playas vírgenes de Colombia.',
      icon: 'Trees',
      maps_url: 'https://maps.google.com/?q=Parque+Nacional+Natural+Tayrona+El+Zaino',
    },
    {
      id: 'dist-9',
      name: 'Bahía de Taganga & Mirador',
      category: 'beach',
      distance: '12 km',
      travel_time: '25 min en taxi',
      description: 'Auténtico pueblo pesquero, escuela de buceo y vistas panorámicas del Caribe.',
      icon: 'Compass',
      maps_url: 'https://maps.google.com/?q=Taganga+Santa+Marta',
    },
    {
      id: 'dist-10',
      name: 'Supermercado Olímpica / Éxito Rodadero',
      category: 'supermarket',
      distance: '900 metros',
      travel_time: '3 min en taxi / 10 min a pie',
      description: 'Gran surtido de víveres, frutas frescas, licores, panadería y droguería.',
      icon: 'ShoppingCart',
      maps_url: 'https://maps.google.com/?q=Supermercado+Exito+Rodadero',
    },
  ],
  recommendations: [
    {
      id: 'rec-1',
      title: 'Restaurante Donde Chucho Blue',
      category: 'restaurant',
      description: 'Famoso por su cazuela de mariscos, pescados frescos y vista espectacular al atardecer.',
      address: 'Playa Salguero',
      distance: 'A 4 min a pie',
      maps_url: 'https://maps.google.com/?q=Donde+Chucho+Blue+Santa+Marta',
    },
    {
      id: 'rec-2',
      title: 'Café Bonsái & Bakery',
      category: 'cafe',
      description: 'Excelente café colombiano de especialidad, desayunos saludables y repostería artesanal.',
      address: 'Calle 23 # 2-18, Rodadero Sur',
      distance: 'A 6 min a pie',
      maps_url: 'https://maps.google.com/?q=Cafe+Bonsai+Santa+Marta',
    },
    {
      id: 'rec-3',
      title: 'Supermercado Éxito Express',
      category: 'supermarket',
      description: 'Ideal para compras rápidas, bebidas, snacks y víveres del día a día.',
      address: 'Carrera 2 con Calle 20',
      distance: 'A 500 metros',
      maps_url: 'https://maps.google.com/?q=Exito+Express+Rodadero+Sur',
    },
    {
      id: 'rec-4',
      title: 'Droguería La Rebaja / Farmacia',
      category: 'pharmacy',
      description: 'Medicamentos, artículos de aseo personal, bloqueador solar y servicio 24 horas a domicilio.',
      address: 'Av. Tamacá # 15-20',
      distance: 'A 800 metros',
      maps_url: 'https://maps.google.com/?q=Drogueria+La+Rebaja+Rodadero',
    },
    {
      id: 'rec-5',
      title: 'Taxis y Transporte Seguro',
      category: 'transport',
      description: 'Recomendamos pedir taxi a través de InDrive o solicitarlo en la portería del edificio.',
      address: 'Portería Principal',
      distance: 'En el lobby',
    },
  ],
  emergency_contacts: [
    {
      id: 'em-1',
      title: 'Recepción & Portería 24H',
      phone: '+57 (605) 420 8899',
      description: 'Guardas de seguridad y administración del edificio',
      icon: 'Shield',
    },
    {
      id: 'em-2',
      title: 'Chat de Airbnb (Soporte Directo)',
      phone: 'Chat de la Reserva',
      description: 'Axel Werner - Atención prioritaria y dudas de la estadía',
      icon: 'MessageSquare',
    },
    {
      id: 'em-3',
      title: 'Línea de Emergencias Nacional',
      phone: '123',
      description: 'Policía Nacional, Bomberos y Ambulancias',
      icon: 'AlertTriangle',
    },
    {
      id: 'em-4',
      title: 'Clínica Portoazul / Centro Médico',
      phone: '+57 (605) 438 0000',
      description: 'Atención médica prioritaria y urgencias',
      icon: 'HeartPulse',
    },
  ],
};

